import 'package:flutter/material.dart';
import '../../core/constants/app_constants.dart';
import '../../data/services/image_storage_service.dart';
import '../../state/expense_store.dart';
class SettingsPage extends StatelessWidget{
 const SettingsPage({super.key,required this.store});final ExpenseStore store;
 Future<void> _clear(BuildContext c)async{final ok=await showDialog<bool>(context:c,builder:(_)=>AlertDialog(title:const Text('Clear all data?'),content:const Text('Delete all expenses and cached receipt images from this device?'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Clear all'))]));if(ok==true){await store.clearAll();await ImageStorageService.clearAll();if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Local data cleared.')));}}
 @override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(20,18,20,120),children:[Text('Settings',style:Theme.of(c).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:20),Card(color:Colors.white,child:Column(children:[const ListTile(leading:Icon(Icons.offline_bolt),title:Text('Offline-first'),subtitle:Text('OCR and expense data stay on the device.')),const Divider(height:1),ListTile(leading:const Icon(Icons.storage),title:const Text('Database'),subtitle:Text(AppConstants.databaseName+' • SQLite')),const Divider(height:1),const ListTile(leading:Icon(Icons.auto_awesome),title:Text('OCR engine'),subtitle:Text('Google ML Kit Text Recognition'))])),const SizedBox(height:16),Card(color:Colors.white,child:const ListTile(leading:Icon(Icons.insights),title:Text('Analytics'),subtitle:Text('Animated CustomPainter donut and weekly bar charts'))),const SizedBox(height:16),Card(color:Theme.of(c).colorScheme.errorContainer,child:ListTile(onTap:()=>_clear(c),leading:const Icon(Icons.delete_sweep),title:const Text('Clear local data'),subtitle:const Text('Delete expenses and receipt cache.')))]));
}
